import type { GameState } from "./types";

export function createInitialState(): GameState {
  return {
    score: 0,
    totalScore: 0,
    bestScore: 0,
    stageIndex: 1,
    combo: 0,
    stage: null,
    stageDone: false,
    stageMistakes: 0,
    stageStartMs: 0,
    stageTransitionMs: 0,
    lastMistake: false,
    complimentHistory: [],
    snake: [],
    prevSnake: [],
    direction: "right",
    nextDirection: "right",
    growBy: 0,
    letters: [],
    boardTools: [],
    activeTools: [],
    toolSpawnCooldownMs: 6000,
    magnetTickMs: 0,
    pause: false,
    moveIntervalMs: 180,
    accumulator: 0,
    clock: 0,
    lastMs: performance.now(),
    touch: { active: false, x: 0, y: 0 },
    kidName: "",
    hudRefreshAtMs: 0,
    expectedKey: "",
    targetFailures: 0,
    targetHintActive: false,
    lastInstantStepMs: -9999,
  };
}
